language: objective-c
osx_image: xcode9
branches:
  only:
  - develop
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - brew update
  - brew outdated carthage || brew upgrade carthage

git:
  submodules: false

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=DirTreeMirror.xcworkspace
  - IOS_FRAMEWORK_SCHEME="DirTreeMirror-iOS"
  - OSX_FRAMEWORK_SCHEME="DirTreeMirror-macOS"
  - TVOS_FRAMEWORK_SCHEME="DirTreeMirror-tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="DirTreeMirror-watchOS"
  matrix:
    - DESTINATION="OS=11.0,name=iPhone X"                   SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="YES"
    - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"            SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="YES"
    - DESTINATION="OS=9.0,name=iPhone 6"                    SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="YES"
    - DESTINATION="OS=8.1,name=iPhone 4s"                   SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="YES"
    - DESTINATION="arch=x86_64"                             SCHEME="$OSX_FRAMEWORK_SCHEME"     RUN_TESTS="YES"
    - DESTINATION="OS=11.0,name=Apple TV 1080p"             SCHEME="$TVOS_FRAMEWORK_SCHEME"    RUN_TESTS="YES"
    - DESTINATION="OS=10.2,name=Apple TV 1080p"             SCHEME="$TVOS_FRAMEWORK_SCHEME"    RUN_TESTS="YES"
    - DESTINATION="OS=9.0,name=Apple TV 1080p"              SCHEME="$TVOS_FRAMEWORK_SCHEME"    RUN_TESTS="YES"
    - DESTINATION="OS=4.0,name=Apple Watch Series 2 - 42mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" RUN_TESTS="NO"
    - DESTINATION="OS=3.1,name=Apple Watch Series 2 - 42mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" RUN_TESTS="NO"
    - DESTINATION="OS=2.0,name=Apple Watch - 38mm"          SCHEME="$WATCHOS_FRAMEWORK_SCHEME" RUN_TESTS="NO"

before_script:
  - sh scripts/bootstrap

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

jobs:
  include:
    - script: pod lib lint --verbose --allow-warnings
    - stage: deploy
      before_deploy: carthage build --no-skip-current && carthage archive DirTreeMirror
      deploy:
        - provider: releases
          api_key:
            secure: KrjeFZFxA8KFpVpZuPpHzjhJREYmOprCR072mGzEJtuf/J9Auiqqml9EEbx0jtabpajkfbDRdWVjkSG+czc13QhBT4uBRCnPiX3c2t1m1PnaZEkiPTyY17ZFIC0+cyxwpQ1KPludHEy5cJ1JS98C6vzprxhSO1p4IDOBMbZ/AmeD8i+iHIGagvdyZdI0ksPuofm9qlg7aQgAvmz+XivlIEtnp9WuDFH0X62Pg2W2M5fJ2IuMTQXAou5Me+/T2TdorGWnASN+7oemYxBHeF1SCkxxvgZ1zh6RDKWaOhBd7+Sim6Aa6KiDpwkIFHtDFw6GVbmpJOp71Ic6PjEOncbXlTvOc+urLcGwUdeGaGOTuyNjKfmrJcvUHUH3E0cvwFvGqXG1C0A8RUIYjRM+RkenxCcEOZPVhYBeZUdS6uHk1ncnQ6r6QTKP0pmbO0uGlhQ4hWUF03u0psAQfQRAYgNsiZPpP/V8Myc0nLrsHK46E+L/CVbuqg82KtcQT2CfYCV4nmG2a3ii/FXaOLJIe0CZqV0uadfXNTYazjdcXXf48OpimNv0hCoaI+od2lMu88Mb08Ff430dNx3k7T5NlWyPLezkT7OfO2dC4MaXkSdS869+G3JKg6mutBLKTAkVuEUMlDqcGSSKFream+D2AVsNKYPWW68XqzzSF6FXrNA8SqA=
          file:
            - Framework.framework.zip
          skip_cleanup: true
          overwrite: true
          on:
            repo: RahulKatariya/DirTreeMirror
            tags: true
        - provider: script
          script: pod trunk push
          on:
            tags: true
